services:
  parsedmarc:
    build:
      context: ./parsedmarc/
      dockerfile: ./Dockerfile
    environment:
      - parsedmarc.general.save_aggregate=True
      - parsedmarc.general.save_forensic=True
      # Adding both common variations for Azure/MSAL cache
      - AZURE_IDENTITY_ALLOW_UNENCRYPTED_STORAGE=True
      - MSAL_CACHE_UNENCRYPTED_STORAGE=True
      - parsedmarc.mail.graph.allow_unencrypted_storage=True
      - parsedmarc.elasticsearch.hosts=http://elasticsearch:9200
      - parsedmarc.elasticsearch.ssl=False
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/:z
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      SERVER_NAME: parsedmarc
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    restart: unless-stopped
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
